sudo: required

language: go

go:
- 1.x
- "1.10"
- 1.11.x
- 1.14.x
- master

services:
    - docker

before_install:
    # install heroku CLI
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to docker registries (dockerhub + heroku)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
    # install deps
    - yarn install
script:
    - go test -v ./...
    #- yarn test
    #- yarn build
    # build docker images
    - docker build -t samihan/go_webapp .
    - docker tag samihan/go_webapp registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
    provider: script
    script:
        # push to dockerhub
        docker push samihan/go_webapp;
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    branch: master